CREATE TABLE "TEST"."FIELDS" (
    "ID"    INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "NAME"    VARCHAR(20) NOT NULL ,
    "FIELD"    CLOB(100000)  LOGGED,
    "RULE"    BLOB(100000)  LOGGED
);

-- Primary key --
ALTER TABLE "TEST"."FIELDS" ADD CONSTRAINT PK_FIELDS PRIMARY KEY (ID);

-- Foreign key(s) --
-- Trigger(s) --
-- Indexes --
CREATE UNIQUE  INDEX TEST.UNQ_FIELDS ON "TEST"."FIELDS" (UPPER(NAME));
;

