CREATE TABLE "TEST"."DEFAULTTEST" (
    "IDX"    INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "TEXT"    VARCHAR(10)  ,
    "CREATED"    TIMESTAMP NOT NULL   DEFAULT CURRENT TIMESTAMP 
);

