CREATE TABLE "TEST"."ID_XML" (
    "ID"    CHAR(16) NOT NULL FOR BIT DATA,
    "NAME"    VARCHAR(50) NOT NULL   DEFAULT '' ,
    "XMLDATA"    XML ,
    "CREATETIME"    TIMESTAMP NOT NULL   DEFAULT CURRENT TIMESTAMP
);
