CREATE TABLE "TEST"."MULTILOB" (
    "ID"    INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "NAME"    VARCHAR(20) NOT NULL ,
    "FIELD1"    CLOB(100000)  LOGGED,
    "FIELD2"    CLOB(100000)  LOGGED,    
    "XMLCOL"   XML,
    "RULE"    BLOB(100000)  LOGGED
);

-- Primary key --
ALTER TABLE "TEST"."MULTILOB" ADD CONSTRAINT PK_FIELDS PRIMARY KEY (ID);
;

